import { LLAMA_API_URL } from "./llamaConfig";

/**
 * Tool support for the local llama.cpp backend.
 *
 * llama.cpp connects to the MCP servers listed in `mcp-servers.json` and
 * exposes them over two endpoints - `GET /tools` to list, `POST /tools` to
 * execute - but it does *not* run the agent loop for you. A chat completion
 * hands tool calls back with `finish_reason: "tool_calls"` and expects the
 * caller to execute them and continue the conversation. That loop lives in
 * converseWithLlama; this module is the plumbing it drives.
 */

/** An OpenAI-shaped function definition, exactly as llama.cpp reports it. */
export type LlamaToolDefinition = {
  type: "function";
  function: {
    name: string;
    description?: string;
    parameters?: unknown;
  };
};

/** A tool invocation requested by the model. */
export type LlamaToolCall = {
  id?: string;
  type?: string;
  function: {
    name: string;
    /** JSON, as a string. Generated by the model, so not necessarily valid. */
    arguments: string;
  };
};

/** Listing tools is a local call, but don't hang the whole reply on it. */
const LIST_TIMEOUT_MS = 5_000;

/** A web search can be slow; this is well short of the chat request timeout. */
const EXECUTE_TIMEOUT_MS = 60_000;

/**
 * Tool output is fed straight back into a 2B model's context. Search results
 * can be enormous, and past a point extra text only slows generation down
 * without improving the answer.
 */
const MAX_TOOL_RESULT_CHARS = 6_000;

/** Tools change only when the server restarts, so re-listing every message is waste. */
const TOOL_CACHE_MS = 60_000;

let cachedTools: { tools: LlamaToolDefinition[]; fetchedAt: number } | null =
  null;

/**
 * Parses the argument blob the model produced.
 *
 * Exported for testing: a small model writing JSON by hand is exactly the thing
 * that goes wrong, and a malformed blob must degrade to "call it with no
 * arguments" rather than throwing and killing the whole reply.
 * @param rawArguments The `arguments` string from a tool call
 * @returns The parsed object, or {} if it wasn't usable
 */
export const parseToolArguments = (
  rawArguments: string | undefined,
): Record<string, unknown> => {
  if (!rawArguments?.trim()) return {};

  try {
    const parsed = JSON.parse(rawArguments);
    // A bare string or array isn't a valid argument map; treat it as absent
    // rather than passing something the tool will reject.
    return parsed && typeof parsed === "object" && !Array.isArray(parsed)
      ? (parsed as Record<string, unknown>)
      : {};
  } catch {
    console.warn("Could not parse tool arguments:", rawArguments);
    return {};
  }
};

/**
 * Flattens whatever `POST /tools` returned into text for the model.
 *
 * llama.cpp answers a successful call with `plain_text_response`, and errors
 * with a `message`. Anything else is passed through as JSON rather than
 * silently dropped - the model can usually still make sense of it.
 * @param payload The parsed response body
 * @returns Text to hand back as the tool result
 */
export const extractToolResultText = (payload: unknown): string => {
  if (typeof payload === "string") return payload;

  if (payload && typeof payload === "object") {
    const body = payload as Record<string, unknown>;

    if (typeof body.plain_text_response === "string") {
      return body.plain_text_response;
    }

    // A failing MCP tool reports `error`; a malformed request to llama.cpp
    // itself reports `message`. Both need to reach the model as text so it can
    // tell the user something useful instead of inventing an answer.
    if (typeof body.error === "string") {
      return `Tool error: ${body.error}`;
    }

    if (typeof body.message === "string") {
      return `Tool error: ${body.message}`;
    }
  }

  return JSON.stringify(payload);
};

/** Trims tool output to something a small model can chew through. */
export const truncateToolResult = (
  text: string,
  limit = MAX_TOOL_RESULT_CHARS,
): string =>
  text.length <= limit
    ? text
    : `${text.slice(0, limit)}\n[...truncated ${text.length - limit} characters]`;

/**
 * Lists the tools llama.cpp is currently exposing.
 *
 * Returns an empty array on any failure, which is also what happens when the
 * server was started without `--mcp-servers-config`. Tools are an enhancement,
 * so losing them must never stop the bot from replying.
 * @returns The available tool definitions, possibly empty
 */
export const getAvailableTools = async (): Promise<LlamaToolDefinition[]> => {
  if (cachedTools && Date.now() - cachedTools.fetchedAt < TOOL_CACHE_MS) {
    return cachedTools.tools;
  }

  try {
    const response = await fetch(`${LLAMA_API_URL}/tools`, {
      signal: AbortSignal.timeout(LIST_TIMEOUT_MS),
    });

    if (!response.ok) {
      // 403 "feature_disabled" is the normal answer when no MCP servers are
      // configured - not worth shouting about.
      console.log(`Tools unavailable from llama.cpp (${response.status})`);
      cachedTools = { tools: [], fetchedAt: Date.now() };
      return [];
    }

    const listed = (await response.json()) as {
      definition?: LlamaToolDefinition;
    }[];

    const tools = listed
      .map((entry) => entry.definition)
      .filter((definition): definition is LlamaToolDefinition => !!definition);

    console.log(
      "Available llama.cpp tools:",
      tools.map((tool) => tool.function.name),
    );

    cachedTools = { tools, fetchedAt: Date.now() };
    return tools;
  } catch (err) {
    console.error("Error listing llama.cpp tools:", err);
    cachedTools = { tools: [], fetchedAt: Date.now() };
    return [];
  }
};

/**
 * Runs one tool call and returns its output as text.
 *
 * Never throws. A failed tool is reported back to the model as the tool's
 * result, so it can apologise or try something else - which is a far better
 * outcome than the whole conversation erroring out because a search timed out.
 * @param toolCall The call the model asked for
 * @returns Tool output, or a description of what went wrong
 */
export const executeToolCall = async (
  toolCall: LlamaToolCall,
): Promise<string> => {
  const name = toolCall.function.name;
  const args = parseToolArguments(toolCall.function.arguments);

  console.log("Executing llama.cpp tool:", { name, args });

  try {
    const response = await fetch(`${LLAMA_API_URL}/tools`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      // `params`, not `arguments`. llama.cpp accepts an `arguments` key without
      // complaint and then passes nothing through, so the tool fails validation
      // rather than erroring here - a silent mismatch worth naming.
      body: JSON.stringify({ tool: name, params: args }),
      signal: AbortSignal.timeout(EXECUTE_TIMEOUT_MS),
    });

    const payload = await response.json().catch(() => null);
    const text = extractToolResultText(payload);

    const trimmed = truncateToolResult(text);
    console.log(
      `Tool ${name} returned ${text.length} characters` +
        (trimmed.length === text.length ? "" : ` (truncated)`),
    );

    return trimmed;
  } catch (err) {
    console.error(`Error executing tool ${name}:`, err);
    return `Tool error: ${name} could not be run (${err}).`;
  }
};
